### PR TITLE
Add error callback to subscription

### PR DESCRIPTION
**Pull request by bitmario**
Currently, if an exception occurs during message processing then it is simply ignored. This PR adds an error callback to the subscriptions, addressing the FIXME in `Client._process_msg`.

**New behavior:**

If an error callback is provided and an exception occurs during message processing, then the error callback is invoked. If the error callback itself raises an exception, then that exception is logged.

### CODE REVIEW

**Comment by bitmario** [comment]
Thanks for merging this.

Any idea why this broke the 3.5 tests though? I couldn't figure out why.

**Comment by wallyqs** [comment]
Not sure either, will have to take a look.

**Comment by wallyqs** [comment]
Sorry for the delay, I will do a release today with this change

**Comment by wallyqs** [comment]
Pushed new version now: https://github.com/nats-io/asyncio-nats-streaming/releases/tag/v0.2.0

**Comment by bitmario** [comment]
Thank you @wallyqs!

**Pull request merged**
